### ISSUE TITLE
Package still on nuget?

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/fable-express#6]
I was unable to install this with the `paket add Fable.Express` command as listed in the readme.
Adding `github fable-compiler/fable-express` to my paket.dependencies did work though.
Is this the new approach?

**Comment by alfonsogarciacaro** [comment]
Sorry, I forgot to remove this repo 😅 The bindings are now in `fable-compiler/fable-import` repo, and the nuget package name is `Fable.Import.Express`.

**Comment by nojaf** [comment]
I see, thanks!
